check for env vars in terraform.tfvars
Summary:
- Check for AWS_ environment variables, and/or set them from terraform.tfvars
- store state to s3 for backup.

Test Plan:
- Unset env vars, ensure they are properly set from values in terraform.tfvars
- check that state is stored in S3 after running ./poutine refresh dev standard

Reviewers: paul, jack.dwyer

Reviewed By: jack.dwyer

Differential Revision: https://phabricator.blueapron.com/D47

diff --git a/poutine b/poutine
--- a/poutine
+++ b/poutine
@@ -6,8 +6,13 @@
 # Maintainer: DevOps Kr3w <devops@blueapron.com>
 # Author: Chris Scholz <scholzie@blueapron.com> // Don't blame plz
 
+[[ $DEBUG ]] && set -x
+
+TF_DIR=./terraform
+
+# Figure out which build roles are valid
 ROLES=()
-pushd roles > /dev/null
+pushd $TF_DIR > /dev/null
 for f in *; do
     if [[ -d "$f" ]]; then
         ROLES+=("$f")
@@ -16,7 +21,6 @@ done
 popd > /dev/null
 [[ $DEBUG ]] && echo "DEBUG: Valid ROLES: ${ROLES[@]}"
 
-#ROLES=(global wms demo standard)
 HELP=("help" "-h" "--help" "-?")
 
 function help {
@@ -27,6 +31,11 @@ function help {
         echo -n "$opt"
     done; echo ""
     exit 1
+}
+
+function get_variable() {
+    # Take in a key="value" and echo the value
+    echo "$1" | awk -F\" '{print $2}'
 }
 
 function check_element_exists() {
@@ -56,39 +65,64 @@ if [ $? -ne 0 ]; then
     help
 fi
 
-# Check for presence of Terraform
-#if which terraform > /dev/null; then # Will only produce output on STDERR
-#    echo "Terraform not found in \$PATH. Please verify installation."
-#    exit 1
-#fi
 
 ACTION="$1"
 ENVIRONMENT="$2"
 ROLE="$3"
 
-TF_REMOTE_STATE_KEY="${USER}_${ROLE}_${ENVIRONMENT}"
-
-TFVARS="roles/${ROLE}/terraform.tfvars"
+TFVARS="${TF_DIR}/${ROLE}/terraform.tfvars"
 # Get the bucket name from the TFVARs file
 BUCKET=$(grep secret_bucket $TFVARS 2>/dev/null)
 if [[ "$?" != "0" ]]; then 
     echo "ERROR: Did not get valid secret_bucket name from $TFVARS"
     exit 1
 else
-    BUCKET=$(echo "$BUCKET" | awk -F\" '{print $2}')
+    BUCKET=$(get_variable $BUCKET)
 fi
 STATE_DIR=$(grep tf_state_bucket_prefix $TFVARS 2>/dev/null)
 if [[ "$?" == 0 ]]; then
-    TF_REMOTE_STATE_KEY="${TF_REMOTE_STATE_KEY}/$(echo "$STATE_DIR" | awk -F\" '{print $2}')"
+    TF_REMOTE_STATE_KEY="${TF_REMOTE_STATE_KEY}/$(get_variable "$STATE_DIR")"
 fi
 [[ $DEBUG ]] && echo "DEBUG: Storing remote state in ${BUCKET}:${TF_REMOTE_STATE_KEY}..."
+
+
+# TODO: Make this a little nicer, if you feel like it.
+# Check for existance of AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID, and
+# AWS_REGION. If they aren't set, try to set them based on values in
+# terraform.tfvars
+if [[ -z "$AWS_ACCESS_KEY_ID" ]]; then
+    AWS_ACCESS_KEY_ID=$(grep -m1 access_key "$TFVARS" 2>/dev/null)
+    export AWS_ACCESS_KEY_ID=$(get_variable "$AWS_ACCESS_KEY_ID")
+    if [[ -z "$AWS_ACCESS_KEY_ID" ]]; then
+        echo "AWS_ACCESS_KEY_ID not set and access_key not found in $TFVARS"
+        exit 1
+    fi
+fi
+if [[ -z "$AWS_SECRET_ACCESS_KEY" ]]; then
+    AWS_SECRET_ACCESS_KEY=$(grep -m1 secret_key "$TFVARS" 2>/dev/null)
+    export AWS_SECRET_ACCESS_KEY=$(get_variable "$AWS_SECRET_ACCESS_KEY")
+    if [[ -z "$AWS_SECRET_ACCESS_KEY" ]]; then
+        echo "AWS_SECRET_ACCESS_KEY not set and secret_key not found in $TFVARS"
+        exit 1
+    fi
+fi
+if [[ -z "$AWS_REGION" ]]; then
+    AWS_DEFAULT_REGION=$(grep -m1 region "$TFVARS" 2>/dev/null)
+    export AWS_DEFAULT_REGION=$(get_variable "$AWS_DEFAULT_REGION")
+    if [[ -z "$AWS_DEFAULT_REGION" ]]; then
+        echo "AWS_DEFAULT_REGION not set and region not found in $TFVARS"
+        exit 1
+    fi
+fi
 
 # Fail on errors and be verbose
 set -ex
 # change to $ROLE directory
-pushd "roles/$ROLE" > /dev/null
+pushd "${TF_DIR}/${ROLE}" > /dev/null
 
+[[ $DEBUG ]] && echo "AAKI: $AWS_ACCESS_KEY_ID ASAK: $AWS_SECRET_ACCESS_KEY ADR: $AWS_DEFAULT_REGION"
 # Set terraform remote config:
+TF_REMOTE_STATE_KEY="${ROLE}_${ENVIRONMENT}"
 terraform remote config -backend="S3" -backend-config="bucket=${BUCKET}" -backend-config="key=${TF_REMOTE_STATE_KEY}"
 
 # Get remote config from S3
@@ -101,8 +135,8 @@ TF_EXIT_CODE=$?
 # Fail on errors again.
 set -e
 
-# Upload tfstate here
-#aws s3 sync --exclude="*" --include="terraform.tfstate" ./ "s3://${BUCKET}/tfstate/${ENVIRONMENT}/${ROLE}/" 
+# Backup tfstate for versioning here, just in case the world blows up
+aws s3 cp .terraform/terraform.tfstate "s3://${BUCKET}/tfstate/${ENVIRONMENT}/${ROLE}/terraform.$(date +%Y-%m-%d-%H%M%S).${USER}.tfstate" 
 
 # GTFO
 popd > /dev/null
